# tmux config
set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g automatic-rename on
# colors
set -g default-terminal "screen-256color"
set -g history-limit 50000

# Vi mode for copy
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
